apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local

resources:
  - ../../base

patches:
  - path: patch.yml
    target:
      kind: Deployment
      name: dbmeta-app
  - path: patch-etl.yml
    target:
      kind: Job
      name: dbmeta-etl
  - path: patch-config.yml
    target:
      kind: ConfigMap
      name: dbmeta-cfg
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: dbmeta-svc
        namespace: local
    target:
      kind: Service
      name: dbmeta-svc
