apiVersion: v1
kind: ConfigMap
metadata:
  name: dbmeta-cfg
  namespace: local
  labels:
    app: dbmeta-app
data:
  LOG_LEVEL: "INFO"
  DATABASE_WH_PORT: "9000"
  DATABASE_WH_PORT_NEW: "9000"
  DATABASE_WH_PORT_V2: "9440"
  DATABASE_WH_SERVER: "192.168.28.176"
  DATABASE_WH_SERVER_NEW: "192.168.28.176"
  DATABASE_WH_SERVER_V2: "rafiki.apegpt.ai"
  DATABASE_WH_DB: "wh"
  DATABASE_WH_DB_NEW: "new_wh"
  DATABASE_WH_DB_V2: "ct"
  DATABASE_WH_PARAMS: "?max_execution_time=120"
  DATABASE_WH_PARAMS_NEW: "?max_execution_time=120"
  DATABASE_WH_PARAMS_V2: "?max_execution_time=120&secure=true&verify=false"
  VECTOR_DB_HOST: "milvus.local"
