apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmeta-app
  namespace: local
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dbmeta-app
    spec:
      imagePullSecrets: []
      containers:
        - name: dbmeta-app
          image: "dbmeta:local"
          imagePullPolicy: Never
