apiVersion: batch/v1
kind: Job
metadata:
  name: dbmeta-etl
  namespace: local
spec:
  template:
    metadata:
      labels:
        app: dbmeta-etl
    spec:
      imagePullSecrets: []
      containers:
        - name: dbmeta-etl
          image: "dbmeta:local"
          imagePullPolicy: Never
