apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local

resources:
  - ../../base

patches:
  - path: patch.yml
    target:
      kind: Deployment
      name: fm-app
  - path: patch-config.yml
    target:
      kind: ConfigMap
      name: fm-app-cfg
  - patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: fm-app-pvc
        namespace: local
      spec:
        storageClassName: local-path
    target:
      kind: PersistentVolumeClaim
      name: fm-app-pvc
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: fm-app-svc
        namespace: local
    target:
      kind: Service
      name: fm-app-svc

# JSON patches to replace volumes completely
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: fm-app
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: gcp-secret
          emptyDir: {}
