apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-app
  namespace: local
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fm-app
          image: "fm_app:local"
          imagePullPolicy: Never
        - name: fm-app-celery
          image: "fm_app:local"
          imagePullPolicy: Never
